from __future__ import annotations

from pathlib import Path
from typing import Any

from .io import read_json
from .network_contract import REQUIRED_EVENTS, validate_network_contract


def _fixture_path(path: str | Path) -> Path:
    root = Path(path)
    return root / "simulated.json" if root.is_dir() else root


def _escape_table(value: Any) -> str:
    return str(value).replace("|", "\\|")


def _validation_table(result: dict[str, Any]) -> list[str]:
    rows = ["| Category | Message |", "|---|---|"]
    errors = result.get("errors") if isinstance(result.get("errors"), list) else []
    warnings = result.get("warnings") if isinstance(result.get("warnings"), list) else []
    if not errors and not warnings:
        rows.append("| ok | fixture passes current simulated network contract |")
        return rows
    rows.extend(f"| error | {_escape_table(error)} |" for error in errors)
    rows.extend(f"| warning | {_escape_table(warning)} |" for warning in warnings)
    return rows


def _event_table(events: Any) -> list[str]:
    rows = ["| # | Kind | Request | Plan | Detail |", "|---:|---|---|---|---|"]
    if not isinstance(events, list) or not events:
        rows.append("| n/a | n/a | n/a | n/a | n/a |")
        return rows
    for idx, event in enumerate(events):
        if not isinstance(event, dict):
            rows.append(f"| {idx} | invalid | n/a | n/a | event is not an object |")
            continue
        detail_parts: list[str] = []
        if "queue_depth" in event:
            detail_parts.append(f"queue_depth={event['queue_depth']}")
        if "elapsed_ms" in event:
            detail_parts.append(f"elapsed_ms={event['elapsed_ms']}")
        detail = ", ".join(detail_parts) if detail_parts else "-"
        rows.append(
            "| {idx} | {kind} | {request} | {plan} | {detail} |".format(
                idx=idx,
                kind=_escape_table(event.get("kind", "missing")),
                request=_escape_table(event.get("request_id", "")),
                plan=_escape_table(event.get("plan_id", "")),
                detail=_escape_table(detail),
            )
        )
    return rows


def render_network_security_spec_draft(fixture: str | Path) -> dict[str, Any]:
    """Render a Phase-0 networking/security/backpressure spec draft."""

    fixture_file = _fixture_path(fixture)
    data = read_json(fixture_file)
    if not isinstance(data, dict):
        raise ValueError("network-contract fixture must contain a JSON object")
    validation = validate_network_contract(fixture_file, mode="simulated")
    markdown = _render_markdown(fixture_file, data, validation)
    return {
        "markdown": markdown,
        "ok": bool(validation.get("ok")),
        "fixture": str(fixture_file),
        "validation": validation,
    }


def _render_markdown(
    fixture_path: Path, fixture: dict[str, Any], validation: dict[str, Any]
) -> str:
    summary = (
        validation.get("summary")
        if isinstance(validation.get("summary"), dict)
        else {}
    )
    events = fixture.get("events")
    required_seen = summary.get("required_events_seen", [])
    missing = sorted(set(REQUIRED_EVENTS) - set(required_seen))
    lines: list[str] = [
        "# Networking, Security, And Backpressure Draft",
        "",
        (
            "Status: DRAFT - generated by `fornax spec network-security`; "
            "not TL/SP sign-off and not a G1 closure claim."
        ),
        "",
        "## Scope And Phase Boundary",
        "",
        (
            "This draft defines the Phase-0/Phase-1a simulated contract for "
            "trust boundary, plan integrity, bounded queues, cancellation, "
            "timeouts, and backpressure. It is a spec and simulated fixture, not "
            "a production transport or security implementation."
        ),
        "",
        "## Source Fixture",
        "",
        f"- Fixture: `{fixture_path}`",
        f"- Version: {fixture.get('version', 'missing')}",
        f"- Mode: {fixture.get('mode', 'missing')}",
        f"- Plan ID: {fixture.get('plan_id', 'missing')}",
        f"- Node ID: {fixture.get('node_id', 'missing')}",
        f"- Max queue depth: {fixture.get('max_queue_depth', 'missing')}",
        f"- Timeout ms: {fixture.get('timeout_ms', 'missing')}",
        f"- Validator status: {'PASS' if validation.get('ok') else 'FAIL'}",
        f"- Required events seen: {required_seen}",
        f"- Missing required events: {missing}",
        "",
        *_validation_table(validation),
        "",
        "## V0 Trust Boundary",
        "",
        (
            "- Phase 1a simulation is a single-process or local-process "
            "trust boundary."
        ),
        (
            "- Cross-node payloads are not product-trusted until Phase 1b+ "
            "lab hardware rules are implemented."
        ),
        (
            "- Every event and payload must carry a non-empty plan ID and "
            "request ID where applicable."
        ),
        (
            "- Payloads with stale or mismatched plan IDs fail closed with "
            "`plan_integrity_reject`."
        ),
        (
            "- Unknown event kinds are warnings in the draft fixture and must "
            "become explicit spec entries before implementation."
        ),
        "",
        "## Node Identity And Endpoint Auth",
        "",
        (
            "- Phase 1a: node identity is a fixture field (`node_id`) and "
            "every simulated worker event is scoped to it."
        ),
        (
            "- Phase 1b trusted lab: node identity and plan ID tags must be "
            "present on every inter-node payload before hardware validation "
            "counts."
        ),
        (
            "- Product deployment: endpoint auth, node admission, audit logs, "
            "and default-deny behavior are required before user traffic."
        ),
        (
            "- The draft does not claim encryption is implemented; encryption "
            "must be implemented or explicitly waived for isolated lab only."
        ),
        "",
        "## Backpressure And Queue Contract",
        "",
        (
            "- Queues are bounded by `max_queue_depth`; enqueue beyond "
            "capacity is an error unless backpressure prevents it first."
        ),
        "- A backpressure event reports `queue_depth == max_queue_depth`.",
        "- Duplicate enqueue for the same request ID is invalid.",
        "- Dequeue of an unknown request ID is invalid.",
        (
            "- Cancellation removes queued work when present and warns when "
            "the request has already left the queue."
        ),
        (
            "- Bounded memory/backpressure must be implemented before Phase "
            "1b hardware validation."
        ),
        "",
        "## Timeout, Retry, Cancel, And Partition Semantics",
        "",
        "- Timeout events must include `elapsed_ms >= timeout_ms` and a request ID.",
        (
            "- Cancellation is terminal for queued work unless a higher-level "
            "replay path creates a new request ID."
        ),
        (
            "- Retry/replay must retain plan ID integrity and must not reuse "
            "transport buffers after cancellation without revalidation."
        ),
        (
            "- Network partition handling is not implemented in Phase 0; "
            "Phase 1+ must define retry budget, replay source, and in-flight "
            "ownership before distributed correctness gates."
        ),
        "",
        "## Simulated Event Trace",
        "",
        *_event_table(events),
        "",
        "## Phase Requirements Matrix",
        "",
        "| Phase | Networking/security/backpressure requirement |",
        "|---|---|",
        (
            "| Phase 1a T1 simulation | Spec exists; bounded queues, "
            "cancellation, timeout, and plan-integrity semantics simulated. |"
        ),
        (
            "| Phase 1b T3 lab hardware | Trusted-lab exception only on "
            "isolated lab network; node identity and plan ID tags implemented; "
            "bounded memory/backpressure implemented. |"
        ),
        (
            "| Phase 3 heterogeneous prototype | Security/backpressure active "
            "for all inter-node payloads; encryption decision implemented or "
            "explicitly waived for lab only. |"
        ),
        (
            "| Product deployment | Endpoint auth, node admission, plan "
            "integrity, encryption posture, audit logs, and failure behavior "
            "documented and enabled by default as appropriate. |"
        ),
        "",
        "## Transport Posture",
        "",
        (
            "- First deterministic transport should be boring: local "
            "process/shm for simulation and TCP for cross-node tests."
        ),
        (
            "- RDMA, UCX/NIXL, and Thunderbolt-IP are optimizations selected "
            "only by measured benefit and platform support."
        ),
        (
            "- Transport selection must not weaken plan-integrity, queue, "
            "timeout, or cancellation semantics."
        ),
        "",
        "## Review Status",
        "",
        (
            "- This draft is reviewable for G1 artifact shape but is not "
            "implementation proof."
        ),
        (
            "- Phase-specific spec-vs-implementation requirements are explicit "
            "here, but hardware and product security work remain gated by "
            "later phases."
        ),
        "",
    ]
    return "\n".join(lines)
