from __future__ import annotations

from datetime import date, datetime, timedelta
from typing import Any


KER_STATUS_VALUES = (
    "unassigned",
    "in-team",
    "hireable",
    "contractable",
    "unavailable",
)
SCOPE_VALUES = ("pending", "full", "narrowed")

_MILESTONES = [
    ("M0 Architecture baseline", "-", "W0", "G0 passed"),
    ("M1 Evidence sprint done", "0", "W1-W4", "G1"),
    ("M2 Pipeline correctness", "1", "W5-W10", "post-G1 placeholder"),
    ("M3 Continuous batching scales", "2", "W9-W13", "G2 with M4"),
    ("M4 MoE expert runtime parity", "2.5", "W11-W17", "G2"),
    ("M5 Heterogeneous frontier serve", "3", "W16-W24", "G3"),
    ("M6 Resilience / elasticity", "4", "W23-W27", "G4"),
    ("M7 Productization / GA", "5", "W27+", "G5"),
]

_ROLES = [
    ("DIST", "High", "Planner, cost model, v0 target contract"),
    ("RT", "Medium", "Runtime format and substrate ADR"),
    ("KER", "Medium", "Apple expert-MLP probe and Apple role decision"),
    ("NET", "Low", "Networking/security draft"),
    ("SRE", "Low-Med", "Preflight workflow and diagnostics"),
    ("PM", "Medium", "Gate, RAID, procurement, staffing"),
    ("TL/SP", "Low", "Review and decide"),
]


def render_program_rebaseline_draft(
    *,
    kickoff_date: str | None = None,
    phase0_weeks: int = 4,
    ker_status: str = "unassigned",
    scope: str = "pending",
) -> dict[str, Any]:
    """Render the Phase-0 roadmap rebaseline and staffing-answer draft."""

    if ker_status not in KER_STATUS_VALUES:
        raise ValueError(f"ker_status must be one of {', '.join(KER_STATUS_VALUES)}")
    if scope not in SCOPE_VALUES:
        raise ValueError(f"scope must be one of {', '.join(SCOPE_VALUES)}")
    if phase0_weeks <= 0:
        raise ValueError("phase0_weeks must be positive")
    kickoff = _parse_date(kickoff_date) if kickoff_date else None
    warnings = _warnings(ker_status=ker_status, scope=scope, kickoff=kickoff)
    markdown = _render_markdown(
        kickoff=kickoff,
        phase0_weeks=phase0_weeks,
        ker_status=ker_status,
        scope=scope,
        warnings=warnings,
    )
    return {
        "markdown": markdown,
        "ok": True,
        "warnings": warnings,
        "kickoff_date": kickoff.isoformat() if kickoff else None,
        "phase0_weeks": phase0_weeks,
        "ker_status": ker_status,
        "scope": scope,
        "staffing_answer": _staffing_answer(ker_status, scope),
    }


def _parse_date(value: str) -> date:
    try:
        return datetime.strptime(value, "%Y-%m-%d").date()
    except ValueError as exc:
        raise ValueError("kickoff_date must use YYYY-MM-DD") from exc


def _warnings(*, ker_status: str, scope: str, kickoff: date | None) -> list[str]:
    warnings: list[str] = []
    if kickoff is None:
        warnings.append("kickoff date is unset; absolute dates are not calculated")
    if ker_status == "unassigned":
        warnings.append("KER staffing answer remains open")
    if ker_status == "unavailable" and scope != "narrowed":
        warnings.append("KER unavailable: Sponsor should narrow Apple role or staff KER before G1")
    if scope == "pending":
        warnings.append("Sponsor scope decision is pending")
    return warnings


def _staffing_answer(ker_status: str, scope: str) -> str:
    if ker_status in {"in-team", "hireable", "contractable"}:
        return "KER staffing path exists; keep Apple expert-worker probe on the Phase-0 board."
    if ker_status == "unavailable" and scope == "narrowed":
        return "KER unavailable and scope narrowed; bias Apple to capacity-only for v0."
    if ker_status == "unavailable":
        return "KER unavailable; G1 must choose NARROW, ITERATE to staff, or KILL."
    return "KER staffing unresolved; G1 cannot silently proceed."


def _render_markdown(
    *,
    kickoff: date | None,
    phase0_weeks: int,
    ker_status: str,
    scope: str,
    warnings: list[str],
) -> str:
    lines: list[str] = [
        "# Roadmap Rebaseline And Staffing Answer Draft",
        "",
        (
            "Status: DRAFT - generated by `fornax program rebaseline`; "
            "not Sponsor approval, not a DEC-005 outcome, and not a G1 closure claim."
        ),
        "",
        "## Inputs",
        "",
        f"- Kickoff date: {kickoff.isoformat() if kickoff else 'unset'}",
        f"- Phase-0 evidence sprint length: {phase0_weeks} weeks",
        f"- KER staffing status: `{ker_status}`",
        f"- Sponsor scope status: `{scope}`",
        "",
        "## Generator Warnings",
        "",
        *_warning_table(warnings),
        "",
        "## Rebaselined Milestone Table",
        "",
        *_milestone_table(kickoff),
        "",
        "## Phase-0 Staffing Matrix",
        "",
        *_staffing_table(ker_status),
        "",
        "## Staffing Answer",
        "",
        _staffing_answer(ker_status, scope),
        "",
        "## G1 Decision Inputs",
        "",
        "| Item | Current generated evidence status | G1 closure rule |",
        "|---|---|---|",
        "| v0 target contract | draft/validation tooling exists; final TL/SP sign-off still open | memory headroom and predicted throughput bar signed off |",
        "| Concurrency-market evidence | contract fields exist; persona evidence still open | persona supplies saturation concurrency or scope narrows |",
        "| Runtime format | generated draft and golden checks exist | reviewed golden-vector method and failure modes |",
        "| Networking/security/backpressure | generated draft and simulated checks exist | reviewed phase-specific spec vs implementation posture |",
        "| MAX/Mojo substrate ADR | generated draft exists | reviewed source precedence, pinned-build policy, alternatives, reversal trigger |",
        "| Apple expert-MLP probe | probe template/validator/role-decision tooling exists; target-Mac measurement still open | measured pass or measured demotion to capacity-only |",
        "| Preflight workflow | command exists and writes doctorable bundle | runnable without oral context |",
        "| Owners/staffing | this draft records KER status; named assignees still external to code | roles assigned or Sponsor accepts narrowed scope |",
        "",
        "## Critical-Path Interpretation",
        "",
        (
            "Phase 1 remains blocked until G1. WS-A target-contract evidence and "
            "WS-D Apple readiness are the two decision paths that can force "
            "ITERATE, NARROW, or KILL."
        ),
        "",
        "## Procurement And Budget Actions",
        "",
        "- Confirm `desktop-minimal` Apple hardware for the S0-7 probe; escalate if absent.",
        "- Keep large spend beyond `desktop-minimal` behind G1 unless Sponsor records a DEC for lead-time reasons.",
        "- If `prosumer-rack` or `lab-reference` orders are placed before G1, record exact SKU/fabric assumptions in the target contract.",
        "",
        "## Review Checklist",
        "",
        "- Absolute dates are filled in after kickoff, or date absence is accepted explicitly.",
        "- KER status is one of in-team, hireable, contractable, unavailable, or unassigned.",
        "- If KER is unavailable, Sponsor chooses NARROW/ITERATE/KILL; silent PROCEED is forbidden.",
        "- Phase 1+ dates remain placeholders until G1/DEC-005.",
        "- The development journal and decision log are updated when G1 outcome is known.",
        "",
    ]
    return "\n".join(lines)


def _warning_table(warnings: list[str]) -> list[str]:
    rows = ["| Category | Message |", "|---|---|"]
    if not warnings:
        rows.append("| ok | no generator warnings |")
        return rows
    rows.extend(f"| warning | {_escape_table(warning)} |" for warning in warnings)
    return rows


def _milestone_table(kickoff: date | None) -> list[str]:
    rows = ["| Milestone | Phase | Window | Date range | Gate |", "|---|---:|---|---|---|"]
    for name, phase, window, gate in _MILESTONES:
        rows.append(
            f"| {name} | {phase} | {window} | {_date_range(kickoff, window)} | {gate} |"
        )
    return rows


def _staffing_table(ker_status: str) -> list[str]:
    rows = ["| Role | Phase-0 load | Required answer | Status |", "|---|---|---|---|"]
    for role, load, answer in _ROLES:
        status = ker_status if role == "KER" else "assign named owner before G1"
        rows.append(f"| {role} | {load} | {answer} | {status} |")
    return rows


def _date_range(kickoff: date | None, window: str) -> str:
    if kickoff is None:
        return "unset"
    if window == "W0":
        return kickoff.isoformat()
    if window.endswith("+"):
        start = _week_number(window[:-1])
        return f"{_week_date(kickoff, start)}+"
    if "-" in window:
        start_text, end_text = window.split("-", 1)
        start = _week_number(start_text)
        end = _week_number(end_text)
        return f"{_week_date(kickoff, start)} to {_week_date(kickoff, end)}"
    return "unset"


def _week_number(value: str) -> int:
    if not value.startswith("W"):
        raise ValueError(f"invalid week marker: {value}")
    return int(value[1:])


def _week_date(kickoff: date, week: int) -> str:
    return (kickoff + timedelta(weeks=week)).isoformat()


def _escape_table(value: Any) -> str:
    return str(value).replace("|", "\\|")
