from __future__ import annotations

from pathlib import Path
from typing import Any

from .io import read_json
from .runtime_format import SUPPORTED_DTYPES, validate_runtime_format_manifest


def _shape_text(value: Any) -> str:
    if isinstance(value, list):
        return "x".join(str(item) for item in value)
    return "missing"


def _len_text(value: Any) -> str:
    return str(len(value)) if isinstance(value, list) else "missing"


def _tolerances_table(tolerances: Any) -> list[str]:
    rows = ["| Dtype | rtol | atol |", "|---|---:|---:|"]
    if not isinstance(tolerances, dict) or not tolerances:
        rows.append("| n/a | n/a | n/a |")
        return rows
    for dtype in sorted(tolerances):
        entry = tolerances[dtype]
        if not isinstance(entry, dict):
            rows.append(f"| {dtype} | n/a | n/a |")
            continue
        rows.append(
            f"| {dtype} | {entry.get('rtol', 'missing')} | "
            f"{entry.get('atol', 'missing')} |"
        )
    return rows


def _escape_table(value: Any) -> str:
    return str(value).replace("|", "\\|")


def _validation_table(result: dict[str, Any]) -> list[str]:
    rows = ["| Category | Message |", "|---|---|"]
    errors = result.get("errors") if isinstance(result.get("errors"), list) else []
    warnings = result.get("warnings") if isinstance(result.get("warnings"), list) else []
    if not errors and not warnings:
        rows.append("| ok | manifest passes current validator with no warnings |")
        return rows
    rows.extend(f"| error | {_escape_table(error)} |" for error in errors)
    rows.extend(f"| warning | {_escape_table(warning)} |" for warning in warnings)
    return rows


def _manifest_path(path: str | Path) -> Path:
    root = Path(path)
    return root / "manifest.json" if root.is_dir() else root


def render_runtime_format_spec_draft(golden: str | Path) -> dict[str, Any]:
    """Render a reviewable Phase-0 runtime-format spec from a golden manifest."""

    manifest_path = _manifest_path(golden)
    manifest = read_json(manifest_path)
    if not isinstance(manifest, dict):
        raise ValueError("runtime-format manifest must contain a JSON object")
    validation = validate_runtime_format_manifest(manifest)
    markdown = _render_markdown(manifest_path, manifest, validation)
    return {
        "markdown": markdown,
        "ok": bool(validation.get("ok")),
        "manifest": str(manifest_path),
        "validation": validation,
    }


def _render_markdown(
    manifest_path: Path, manifest: dict[str, Any], validation: dict[str, Any]
) -> str:
    activation = (
        manifest.get("activation")
        if isinstance(manifest.get("activation"), dict)
        else {}
    )
    kv_page = (
        manifest.get("kv_page")
        if isinstance(manifest.get("kv_page"), dict)
        else {}
    )
    expert_batch = (
        manifest.get("expert_batch")
        if isinstance(manifest.get("expert_batch"), dict)
        else {}
    )
    lines: list[str] = [
        "# Runtime Format And Invariants Draft",
        "",
        (
            "Status: DRAFT - generated by `fornax spec runtime-format`; "
            "not TL sign-off and not a G1 closure claim."
        ),
        "",
        "## Scope",
        "",
        (
            "This draft defines the Phase-0 review contract for activation "
            "payloads, KV pages, and routed expert batches. It is intentionally "
            "a format and correctness artifact, not an optimized runtime "
            "implementation."
        ),
        "",
        "## Source Golden Vector",
        "",
        f"- Manifest: `{manifest_path}`",
        f"- Manifest version: {manifest.get('version', 'missing')}",
        f"- Validator status: {'PASS' if validation.get('ok') else 'FAIL'}",
        "",
        * _validation_table(validation),
        "",
        "## Activation Tensor",
        "",
        f"- Dtype: {activation.get('dtype', 'missing')}",
        f"- Shape: {_shape_text(activation.get('shape'))}",
        f"- Layout: {activation.get('layout', 'missing')}",
        f"- Golden payload values: {_len_text(activation.get('values'))}",
        "- Strides: implicit contiguous row-major strides derived from shape.",
        (
            "- Alignment: implementation must declare backend alignment before "
            "optimized transport is trusted; Phase-0 vectors are "
            "alignment-neutral JSON values."
        ),
        (
            "- Padding: no implicit padding is allowed in the logical payload; "
            "padded transports must carry logical shape and valid element count."
        ),
        (
            "- Residency: producer owns the source buffer until handoff is "
            "acknowledged by the receiving stage."
        ),
        (
            "- Lifetime: receivers may reuse buffers only after the request/plan "
            "boundary confirms no replay or retry needs the payload."
        ),
        (
            "- Send/receive reuse: sender and receiver must agree on request ID, "
            "plan ID, dtype, shape, and logical element count before either side "
            "reuses a transport buffer."
        ),
        "",
        "## KV Page",
        "",
        f"- Dtype: {kv_page.get('dtype', 'missing')}",
        f"- Shape: {_shape_text(kv_page.get('shape'))}",
        f"- Page size: {kv_page.get('page_size', 'missing')}",
        f"- Token count: {kv_page.get('token_count', 'missing')}",
        f"- Owner stage: {kv_page.get('owner_stage', 'missing')}",
        (
            "- Ownership: exactly one stage owns mutation rights for a KV page "
            "at a time."
        ),
        (
            "- Eviction: eviction requires plan/request ID, owner stage, page "
            "index, and replay-safe invalidation."
        ),
        (
            "- Transfer: transfer must preserve page size, token count, dtype, "
            "owner stage, and logical token order."
        ),
        (
            "- Replay: a replayed request must either reuse a validated page "
            "for the same plan ID or rebuild the page from the reference path."
        ),
        "",
        "## Expert Batch",
        "",
        f"- Layer ID: {expert_batch.get('layer_id', 'missing')}",
        f"- Expert IDs: {expert_batch.get('expert_ids', 'missing')}",
        f"- Token indices: {expert_batch.get('token_indices', 'missing')}",
        f"- Top-k weights: {expert_batch.get('topk_weights', 'missing')}",
        f"- Hidden shape: {_shape_text(expert_batch.get('hidden_shape'))}",
        f"- Gather order: {expert_batch.get('gather_order', 'missing')}",
        (
            "- Routing metadata: plan ID, layer ID, expert ID, source stage, "
            "destination worker, and packed token position are required before "
            "Phase 1 transport."
        ),
        (
            "- Gather rule: `gather_order` is a permutation of packed token "
            "positions; duplicate or missing positions are malformed."
        ),
        "",
        "## Quantization And Dtypes",
        "",
        (
            "- Supported in-flight payload dtypes in the Phase-0 validator: "
            f"{sorted(SUPPORTED_DTYPES)}"
        ),
        (
            "- Weight-only formats such as q4/q8 are allowed for at-rest model "
            "weights, not activation/KV/expert hidden payloads."
        ),
        (
            "- Expert weight quantization must be named in the target contract "
            "before Apple expert-worker gating can pass."
        ),
        "",
        "## Failure Modes",
        "",
        (
            "- Malformed shape, dtype, token count, gather order, or non-finite "
            "top-k weight: reject the payload and surface a contract error."
        ),
        (
            "- Stale plan ID or mismatched owner stage: reject the payload and "
            "require replay/rebuild from the reference path."
        ),
        (
            "- Unsupported dtype on a backend: fail closed at placement or "
            "handoff, never silently reinterpret bytes."
        ),
        "- KV page token_count greater than page_size: reject before transport.",
        "- Expert batch with duplicated gather positions: reject before dispatch.",
        "",
        "## Reference Path And Golden-Vector Method",
        "",
        (
            "- The reference path is slow and obvious: deserialize the JSON "
            "golden vector, validate it, and compare optimized backend payloads "
            "against the same logical values."
        ),
        (
            "- Reference comparisons use the same placement plan, owner stage, "
            "routing metadata, and gather order as the optimized handoff under "
            "test."
        ),
        (
            "- Golden vectors must include activation, KV page, expert batch, "
            "and per-dtype tolerances."
        ),
        (
            "- No optimized cross-vendor path is trusted until it passes the "
            "golden vectors within the declared per-dtype tolerances."
        ),
        "",
        "## Per-Dtype Tolerances",
        "",
        * _tolerances_table(manifest.get("tolerances")),
        "",
        "## Build And Toolchain Assumptions",
        "",
        (
            "- Linux NVIDIA/AMD and macOS Apple Silicon backends must name "
            "their MAX/Mojo/runtime build before performance evidence is "
            "accepted."
        ),
        (
            "- Phase-0 JSON vectors are model-free and CI-safe; accelerator-"
            "specific binary layouts must be proven equivalent to this logical "
            "contract."
        ),
        (
            "- Backend-specific alignment or padding is an implementation detail "
            "unless it changes the logical shape, dtype, owner, or gather "
            "semantics."
        ),
        "",
    ]
    return "\n".join(lines)
